export type Product = {
    id: number
    name: string
    price: number
    image: string
    category: string
    flavor?: string
    featured?: boolean
}

export const products: Product[] = [
    {
        id: 1,
        name: "Belgian Choco Almond Jar Ina Cookies",
        price: 85000,
        image: "/images/30_SKU_IC_lebaran-53.webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
    },
    {
        id: 2,
        name: "Blueberry Button Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-45.webp",
        category: "Ina Cookies",
        flavor: "Blueberry",
    },
    {
        id: 3,
        name: "Broccoli Australian Cheese Puffs Kukids",
        price: 19000,
        image: "/images/Asset-2-1.png",
        category: "Kukids",
        flavor: "Cheese",
    },
    {
        id: 4,
        name: "Character Animal Kukids",
        price: 80000,
        image: "/images/25_sku_dailyproduct-05.webp",
        category: "Kukids",
    },
    {
        id: 5,
        name: "Character Princess Kukids",
        price: 80000,
        image: "/images/25_sku_dailyproduct-06.webp",
        category: "Kukids",
    },
    {
        id: 6,
        name: "Character Superhero Kukids",
        price: 80000,
        image: "/images/25_sku_dailyproduct-07.webp",
        category: "Kukids",
    },
    {
        id: 7,
        name: "Character Unicorn Kukids",
        price: 80000,
        image: "/images/25_sku_dailyproduct-04.webp",
        category: "Kukids",
    },
    {
        id: 8,
        name: "Cheesy Almond White Jar Ina Cookies",
        price: 85000,
        image: "/images/30_SKU_IC_lebaran-74.webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 9,
        name: "Cheesy Almond White Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-72.webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 10,
        name: "Chicken Mushroom Puffs Kukids",
        price: 19000,
        image: "/images/Asset-1-1.png",
        category: "Kukids",
        flavor: "Chicken Mushroom",
    },
    {
        id: 11,
        name: "Choco Almond Vegan Jar Ina Cookies",
        price: 85000,
        image: "/images/30_SKU_IC_lebaran-42.webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
    },
    {
        id: 12,
        name: "Choco Almond Vegan Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-40.webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
    },
    {
        id: 13,
        name: "Choco Mede Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-62.webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
    },
    {
        id: 14,
        name: "Choco Milky Puffs Kukids",
        price: 19000,
        image: "/images/Asset-3.png",
        category: "Kukids",
        flavor: "Chocolate",
    },
    {
        id: 15,
        name: "Choco Pop Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-67 (1).webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
    },
    {
        id: 16,
        name: "Cokelat Mede Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-60.webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
    },
    {
        id: 17,
        name: "DIY Blind Bucket Boy Kukids",
        price: 80000,
        image: "/images/25_sku_dailyproduct-08.webp",
        category: "Kukids",
    },
    {
        id: 18,
        name: "DIY Blind Bucket Girl Kukids",
        price: 80000,
        image: "/images/25_sku_dailyproduct-09.webp",
        category: "Kukids",
    },
    {
        id: 19,
        name: "DIY Cookies Choco Ball Kukids",
        price: 80000,
        image: "/images/25_sku_dailyproduct-11.webp",
        category: "Kukids",
        flavor: "Chocolate",
    },
    {
        id: 20,
        name: "DIY Cookies Choco Crunchy Kukids",
        price: 80000,
        image: "/images/25_sku_dailyproduct-10.webp",
        category: "Kukids",
        flavor: "Chocolate",
    },
    {
        id: 21,
        name: "Green Tea Almond Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-54.webp",
        category: "Ina Cookies",
        flavor: "Green Tea",
    },
    {
        id: 22,
        name: "Jual Kue Kering Putri Salju – Kue Putri Salju – Camilan Lezat dan Sehat dari Ina Cookies",
        price: 85000,
        image: "/images/4_sku_allvariant-37.webp",
        category: "Ina Cookies",
        featured: true,
    },
    {
        id: 23,
        name: "Jual Kue Kering Putri Salju Keju Reguler – Kue Putri Salju Keju – Camilan Lezat dan Sehat dari Ina Cookies",
        price: 135000,
        image: "/images/4_sku_allvariant-38 (1).webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 24,
        name: "Jual Kue Kering Putri Salju Reguler – Putri Salju – Ina Cookies",
        price: 135000,
        image: "/images/4_sku_allvariant-35.webp",
        category: "Ina Cookies",
        featured: true,
    },
    {
        id: 25,
        name: "Jual Kukis Almond Cheese Chocolate Reguler – Ina Cookies",
        price: 135000,
        image: "/images/4_sku_allvariant-01 (1).webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
    },
    {
        id: 26,
        name: "Jual Kukis Belgian Choco Almond Reguler Ina Cookies – Camilan Cokelat Lezat dan Renyah",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-51.webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
        featured: true,
    },
    {
        id: 27,
        name: "Jual Kukis Cheese Kress Reguler – Kukis Keju – Ina Cookies",
        price: 135000,
        image: "/images/4_sku_allvariant-05 (1).webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 28,
        name: "Jual Kukis Cheese Kress Ukuran Jar – Kukis Keju – Ina Cookies",
        price: 85000,
        image: "/images/4_sku_allvariant-07.webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 29,
        name: "Jual Kukis Green Tea Almond Ukuran Jar – Camilan Lezat dan Sehat dari Ina Cookies",
        price: 85000,
        image: "/images/4_sku_allvariant-10.webp",
        category: "Ina Cookies",
        flavor: "Green Tea",
    },
    {
        id: 30,
        name: "Jual Kukis Kastengel Keju Ina Cookies Ukuran Jar – Ina Cookies",
        price: 85000,
        image: "/images/4_sku_allvariant-13.webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 31,
        name: "Jual Kukis Kombinasi Asin – Kaastangel, Cheese Stick, Cheese Kress, dan Putri Cheese Nut – Ina Cookies",
        price: 170000,
        image: "/images/4_sku_allvariant-14.webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 32,
        name: "Jual Kukis Kombinasi Kue Cokelat Ina Cookies – Kue Putri Ina, Almond Cheese Chocolate, Putri Es Krim dan Green Tea Almond.",
        price: 170000,
        image: "/images/4_sku_allvariant-17.webp",
        category: "Ina Cookies",
        flavor: "Assorted",
    },
    {
        id: 33,
        name: "Jual Kukis Kombinasi Nastar – Ina Cookies",
        price: 170000,
        image: "/images/4_sku_allvariant-18.webp",
        category: "Ina Cookies",
        featured: true,
    },
    {
        id: 34,
        name: "Jual Kukis Milky Nastar Reguler Ina Cookies – Camilan Lezat untuk Setiap Momen",
        price: 135000,
        image: "/images/4_sku_allvariant-22 (1).webp",
        category: "Ina Cookies",
    },
    {
        id: 35,
        name: "Jual Kukis Nastar Keju Ukuran Jar Ina Cookies",
        price: 85000,
        image: "/images/4_sku_allvariant-26.webp",
        category: "Ina Cookies",
        flavor: "Cheese",
        featured: true,
    },
    {
        id: 36,
        name: "Jual Kukis Nastar Keju Ukuran Reguler Ina Cookies",
        price: 135000,
        image: "/images/4_sku_allvariant-24 (1).webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 37,
        name: "Jual Kukis Nastar Polos Reguler Ina Cookies – Cita Rasa Nastar Klasik yang Lezat",
        price: 135000,
        image: "/images/4_sku_allvariant-27.webp",
        category: "Ina Cookies",
    },
    {
        id: 38,
        name: "Jual Kukis Putri Red Velvet Ukuran Jar – Camilan Manis dari Ina Cookies",
        price: 85000,
        image: "/images/4_sku_allvariant-34.webp",
        category: "Ina Cookies",
        flavor: "Red Velvet",
    },
    {
        id: 39,
        name: "Jual Kukis Putri Red Velvet Ukuran Reguler – Camilan Manis dari Ina Cookies",
        price: 135000,
        image: "/images/4_sku_allvariant-32.webp",
        category: "Ina Cookies",
        flavor: "Red Velvet",
        featured: true,
    },
    {
        id: 40,
        name: "Kaastengels Mocaf Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-43 (1).webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 41,
        name: "Kaastengels Reguler Ina Cookies",
        price: 135000,
        image: "/images/4_sku_allvariant-11 (1).webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 42,
        name: "Kombinasi Manis Ina Cookies",
        price: 170000,
        image: "/images/30_SKU_IC_lebaran-83.webp",
        category: "Ina Cookies",
        flavor: "Assorted",
    },
    {
        id: 43,
        name: "Kue Kering Sagu Keju Jar – Kue Sagu Keju – Kue Ina Cookies",
        price: 85000,
        image: "/images/4_sku_allvariant-45.webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 44,
        name: "Kue Kering Sagu Keju Ukuran Reguler – Kue Sagu Keju – Ina Cookies Sagu Keju",
        price: 135000,
        image: "/images/4_sku_allvariant-43.webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 45,
        name: "Kue Kering Skippy Mede Coklat Jar – Kue Skippy Mede Coklat – Ina Cookies",
        price: 85000,
        image: "/images/4_sku_allvariant-48-1.webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
    },
    {
        id: 46,
        name: "Kue Kering Skippy Mede Coklat Reguler – Kue Skippy Mede Coklat – Ina Cookies",
        price: 135000,
        image: "/images/4_sku_allvariant-46.webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
    },
    {
        id: 47,
        name: "Kukis Chessy Almond White Jar – Kue Chessy Almond White- Kukis Chessy Almond White Ina Cookies",
        price: 85000,
        image: "/images/4_sku_allvariant-42.webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 48,
        name: "Mango Velvet Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-47.webp",
        category: "Ina Cookies",
        flavor: "Mango",
    },
    {
        id: 49,
        name: "Mini Cookies Choco Sprinkle Ina Cookies",
        price: 35000,
        image: "/images/25_sku_dailyproduct-13.webp",
        category: "Mini Cookies",
        flavor: "Chocolate",
    },
    {
        id: 50,
        name: "Mini Cookies Golden Cheese Ina Cookies",
        price: 35000,
        image: "/images/25_sku_dailyproduct-15.webp",
        category: "Mini Cookies",
        flavor: "Cheese",
    },
    {
        id: 51,
        name: "Mini Cookies Kastangel Ina Cookies",
        price: 35000,
        image: "/images/25_sku_dailyproduct-16.webp",
        category: "Mini Cookies",
        flavor: "Cheese",
    },
    {
        id: 52,
        name: "Mini Cookies Nastar Keju Ina Cookies",
        price: 35000,
        image: "/images/25_sku_dailyproduct-17.webp",
        category: "Mini Cookies",
        flavor: "Cheese",
    },
    {
        id: 53,
        name: "Mini Croissant Cheese Classique Ina Cookies",
        price: 35000,
        image: "/images/25_sku_dailyproduct-12.webp",
        category: "Mini Cookies",
        flavor: "Cheese",
    },
    {
        id: 54,
        name: "Mini Croissant Cinnamon Le Sucre Ina Cookies",
        price: 35000,
        image: "/images/25_sku_dailyproduct-14.webp",
        category: "Mini Cookies",
        flavor: "Cinnamon",
    },
    {
        id: 55,
        name: "Nastar Kurma Reguler Ina Cookies",
        price: 135000,
        image: "/images/25_sku_dailyproduct-14.webp",
        category: "Ina Cookies",
        flavor: "Date",
    },
    {
        id: 56,
        name: "Palm Cheese Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-38.webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 57,
        name: "Peanut Butter Jar Ina Cookies",
        price: 85000,
        image: "/images/30_SKU_IC_lebaran-33.webp",
        category: "Ina Cookies",
        flavor: "Peanut Butter",
    },
    {
        id: 58,
        name: "Peanut Butter Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-31.webp",
        category: "Ina Cookies",
        flavor: "Peanut Butter",
    },
    {
        id: 59,
        name: "Pie Nastar Blueberry Isi 10 – Naslem",
        price: 40000,
        image: "/images/naslem-blueberry-10.png",
        category: "Naslem",
        flavor: "Blueberry",
    },
    {
        id: 60,
        name: "Pie Nastar Blueberry Isi 6 – Naslem",
        price: 25000,
        image: "/images/naslem-blueberry-6.png",
        category: "Naslem",
        flavor: "Blueberry",
    },
    {
        id: 61,
        name: "Pie Nastar Cokelat Isi 10 – Naslem",
        price: 40000,
        image: "/images/naslem-coklat-10.png",
        category: "Naslem",
        flavor: "Chocolate",
    },
    {
        id: 62,
        name: "Pie Nastar Cokelat Isi 6 – Naslem",
        price: 25000,
        image: "/images/naslem-coklat-6.png",
        category: "Naslem",
        flavor: "Chocolate",
    },
    {
        id: 63,
        name: "Pie Nastar Cokelat Nanas Isi 10 – Naslem",
        price: 40000,
        image: "/images/naslem-coklat-nanas-10.png",
        category: "Naslem",
        flavor: "Chocolate Pineapple",
    },
    {
        id: 64,
        name: "Pie Nastar Cokelat Nanas Isi 6 – Naslem",
        price: 25000,
        image: "/images/naslem-coklat-nanas-6.png",
        category: "Naslem",
        flavor: "Chocolate Pineapple",
    },
    {
        id: 65,
        name: "Pie Nastar Original Isi 10 – Naslem",
        price: 40000,
        image: "/images/naslem-ori-10.png",
        category: "Naslem",
        flavor: "Original",
    },
    {
        id: 66,
        name: "Pie Nastar Original Isi 6 – Naslem",
        price: 25000,
        image: "/images/naslem-ori-6.png",
        category: "Naslem",
        flavor: "Original",
    },
    {
        id: 67,
        name: "Pie Nastar Pistachio Isi 10 – Naslem",
        price: 40000,
        image: "/images/30_sku_naslem_web-01.webp",
        category: "Naslem",
        flavor: "Pistachio",
    },
    {
        id: 68,
        name: "Pie Nastar Pistachio Isi 6 – Naslem",
        price: 25000,
        image: "/images/30_sku_naslem_web-02.webp",
        category: "Naslem",
        flavor: "Pistachio",
    },
    {
        id: 69,
        name: "Pie Nastar Tiramisu Isi 10 – Naslem",
        price: 40000,
        image: "/images/Untitled-2-02.png",
        category: "Naslem",
        flavor: "Tiramisu",
    },
    {
        id: 70,
        name: "Pie Nastar Tiramisu Isi 6 – Naslem",
        price: 25000,
        image: "/images/Untitled-2-01-768x768.png",
        category: "Naslem",
        flavor: "Tiramisu",
    },
    {
        id: 71,
        name: "Putri Cheese Nut Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-09 (1).webp",
        category: "Ina Cookies",
        flavor: "Cheese",
    },
    {
        id: 72,
        name: "Putri Choco Rocher Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-77.webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
        featured: true,
    },
    {
        id: 73,
        name: "Putri Cinnamon Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-34.webp",
        category: "Ina Cookies",
        flavor: "Cinnamon",
    },
    {
        id: 74,
        name: "Putri Cokelat Jar Ina Cookies",
        price: 85000,
        image: "/images/30_SKU_IC_lebaran-71.webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
    },
    {
        id: 75,
        name: "Putri Cokelat Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-69.webp",
        category: "Ina Cookies",
        flavor: "Chocolate",
    },
    {
        id: 76,
        name: "Putri Es Krim Jar Ina Cookies",
        price: 85000,
        image: "/images/30_SKU_IC_lebaran-66.webp",
        category: "Ina Cookies",
        flavor: "Ice Cream",
    },
    {
        id: 77,
        name: "Putri Es Krim Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-64.webp",
        category: "Ina Cookies",
        flavor: "Ice Cream",
    },
    {
        id: 78,
        name: "Putri Ina Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-75.webp",
        category: "Ina Cookies",
        featured: true,
    },
    {
        id: 79,
        name: "Skippy Mede Putih Jar Ina Cookies",
        price: 85000,
        image: "/images/",
        category: "Ina Cookies",
        flavor: "Cashew",
    },
    {
        id: 80,
        name: "Skippy Mede Putih Reguler Ina Cookies",
        price: 135000,
        image: "/images/30_SKU_IC_lebaran-79.webp",
        category: "Ina Cookies",
        flavor: "Cashew",
    },
]

